services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        NEXT_PUBLIC_DOMAIN: ${DOMAIN:-xneine.site}
    container_name: mailol-app
    restart: unless-stopped
    ports:
      - "3000:3000"
    networks:
      - mailol-net
    environment:
      - NODE_ENV=${NODE_ENV}
      - DOMAIN=${DOMAIN:-xneine.site}
      - REDIS_URL=${REDIS_URL}
      - JWT_SECRET=${JWT_SECRET:-super-secret-jwt-hash-value-for-mailol-production}
      - JWT_EXPIRY=${JWT_EXPIRY:-3600}
      - DEFAULT_QUOTA=${DEFAULT_QUOTA:-41943040}

  mta:
    build:
      context: .
      dockerfile: Dockerfile.haraka
      args:
        DOMAIN: ${DOMAIN:-xneine.site}
    container_name: mailol-mta
    restart: unless-stopped
    ports:
      - "25:25"
    networks:
      - mailol-net
    environment:
      - REDIS_URL=${REDIS_URL}

networks:
  mailol-net:
    name: mailol-net
    driver: bridge
  redis-net:
    name: redis-net
    external: true